# Generated by Django 4.0.5 on 2022-06-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peak', models.IntegerField()),
                ('lowestpoint', models.IntegerField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hikehunter.difficulty')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hikehunter.region')),
            ],
        ),
    ]
