# Generated by Django 4.0.5 on 2022-06-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0004_alter_hike_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='terrain',
            field=models.CharField(choices=[('FO', 'Forest'), ('FI', 'Fields'), ('RO', 'Rocks'), ('ME', 'Meadows'), ('MI', 'Mixed')], default='MI', max_length=50, verbose_name='Terrain'),
        ),
    ]
