# Generated by Django 4.0.5 on 2022-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0005_alter_hike_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('MS', 'Moderately Strenuous'), ('S', 'Strenuous'), ('VS', 'Very Strenuous')], default='E', max_length=50, verbose_name='Difficulty'),
        ),
    ]
