# Generated by Django 4.0.5 on 2022-06-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0008_alter_hike_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
