# Generated by Django 4.0.5 on 2022-06-09 18:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0009_remove_hike_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
