# Generated by Django 4.0.5 on 2022-06-10 09:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0010_alter_hike_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
