# Generated by Django 4.0.5 on 2022-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0011_hike_image_alter_hike_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='image',
        ),
    ]
