# Generated by Django 4.0.5 on 2022-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0012_remove_hike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
