# Generated by Django 4.0.5 on 2022-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikehunter', '0015_alter_hike_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Moderately Strenuous', 'Moderately Strenuous'), ('Strenuous', 'Strenuous'), ('Very Strenuous', 'Very Strenuous')], default='E', max_length=50, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='region',
            field=models.CharField(choices=[('Hlavní město Praha', 'Hlavní město Praha'), ('Středočeský kraj', 'Středočeský kraj'), ('Jihočeský kraj', 'Jihočeský kraj'), ('Plzeňský kraj', 'Plzeňský kraj'), ('Karlovarský kraj', 'Karlovarský kraj'), ('Ústecký kraj', 'Ústecký kraj'), ('Liberecký kraj', 'Liberecký kraj'), ('Královéhradecký kraj', 'Královéhradecký kraj'), ('Pardubický kraj', 'Pardubický kraj'), ('Kraj Vysočina', 'Kraj Vysočina'), ('Jihomoravský kraj', 'Jihomoravský kraj'), ('Zlínský kraj', 'Zlínský kraj'), ('Olomoucký kraj', 'Olomoucký kraj'), ('Moravskoslezský kraj', 'Moravskoslezský kraj')], max_length=50, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='terrain',
            field=models.CharField(choices=[('Forest', 'Forest'), ('Fields', 'Fields'), ('Rocks', 'Rocks'), ('Meadows', 'Meadows'), ('Mixed', 'Mixed')], default='MI', max_length=50, verbose_name='Terrain'),
        ),
    ]
